/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.armando.prj_clinicahospitalar.front;

import com.armando.prj_clinicahospitalar.back.Endereco;
import com.armando.prj_clinicahospitalar.back.ContatoTelEmail;
import com.armando.prj_clinicahospitalar.back.Enfermeiro;
import com.armando.prj_clinicahospitalar.back.Genero;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Armando
 */
public class GerenciarEnfermeiros extends javax.swing.JFrame {

    DefaultComboBoxModel dm = new DefaultComboBoxModel();

    void preencherComboBox() {
        //Função para preencher o combobox de enfermeiros
        dm = new DefaultComboBoxModel();
        cmbEnfermeiros.setModel(dm);
        for (int i = 0; i < HomePage.enfermeiros.size(); i++) {
            dm.addElement(String.valueOf(HomePage.enfermeiros.get(i).getNomeCompleto()));
            cmbEnfermeiros.setModel(dm);
        }
    }

    void clearFields() {
        //Função para limpar os campos de cadastro
        txtNome.setText("");
        txtBairro.setText("");
        txtCEP.setText("");
        txtCel.setText("");
        txtCidade.setText("");
        txtEmail.setText("");
        txtEstado.setText("");
        txtNum.setText("");
        txtRua.setText("");
        txtTel.setText("");
        rdFem.setSelected(false);
        rdMasc.setSelected(false);
        dtDataNasc.setCalendar(null);
        rdSim1.setSelected(false);
        rdNao1.setSelected(false);
        txtSetor1.setText("");
        txtCH1.setText("");

    }

    void clearFields2() {
        //Função para limpar os campos de edição
        txtNome1.setText("");
        txtBairro1.setText("");
        txtCEP1.setText("");
        txtCel1.setText("");
        txtCidade1.setText("");
        txtEmail1.setText("");
        txtEstado1.setText("");
        txtNum1.setText("");
        txtRua1.setText("");
        txtTel1.setText("");
        rdFem2.setSelected(false);
        rdMasc2.setSelected(false);
        dtDataNasc1.setCalendar(null);
        rdSim2.setSelected(false);
        rdNao2.setSelected(false);
        txtSetor2.setText("");

    }

    public GerenciarEnfermeiros() {
        initComponents();
        //preenche o combobox caso haja enfermeiro cadastrado
        if (HomePage.enfermeiros.size() > 0) {
            preencherComboBox();
        }
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelDados = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        painelDadoPessoal = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblDtNasc = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        dtDataNasc = new com.toedter.calendar.JDateChooser();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        lblCel = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        painelEnfermeiro = new javax.swing.JPanel();
        panelRX = new javax.swing.JPanel();
        rdSim1 = new javax.swing.JRadioButton();
        rdNao1 = new javax.swing.JRadioButton();
        lblSetor1 = new javax.swing.JLabel();
        txtSetor1 = new javax.swing.JTextField();
        lblCH1 = new javax.swing.JLabel();
        txtCH1 = new javax.swing.JTextField();
        panelGenero = new javax.swing.JPanel();
        rdMasc = new javax.swing.JRadioButton();
        rdFem = new javax.swing.JRadioButton();
        btnVoltar1 = new javax.swing.JToggleButton();
        panelCRUD = new javax.swing.JPanel();
        cmbEnfermeiros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        painelDadoPessoal1 = new javax.swing.JPanel();
        lblNome1 = new javax.swing.JLabel();
        lblDtNasc1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        dtDataNasc1 = new com.toedter.calendar.JDateChooser();
        lblRua1 = new javax.swing.JLabel();
        txtRua1 = new javax.swing.JTextField();
        lblNum1 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        txtBairro1 = new javax.swing.JTextField();
        lblBairro1 = new javax.swing.JLabel();
        lblCidade1 = new javax.swing.JLabel();
        txtCidade1 = new javax.swing.JTextField();
        lblEstado1 = new javax.swing.JLabel();
        txtEstado1 = new javax.swing.JTextField();
        lblCEP1 = new javax.swing.JLabel();
        txtCEP1 = new javax.swing.JTextField();
        txtTel1 = new javax.swing.JTextField();
        lblTel1 = new javax.swing.JLabel();
        txtCel1 = new javax.swing.JTextField();
        lblCel1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        painelEnfermeiro1 = new javax.swing.JPanel();
        panelRX1 = new javax.swing.JPanel();
        rdSim2 = new javax.swing.JRadioButton();
        rdNao2 = new javax.swing.JRadioButton();
        lblSetor2 = new javax.swing.JLabel();
        txtSetor2 = new javax.swing.JTextField();
        lblCH2 = new javax.swing.JLabel();
        txtCH2 = new javax.swing.JTextField();
        panelGenero2 = new javax.swing.JPanel();
        rdMasc2 = new javax.swing.JRadioButton();
        rdFem2 = new javax.swing.JRadioButton();
        btnAlterar = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Enfermeiros");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        painelDados.setBackground(new java.awt.Color(255, 255, 255));
        painelDados.setPreferredSize(new java.awt.Dimension(800, 300));
        painelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastrar Enfermeiros");
        lblTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelDados.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        painelDadoPessoal.setBackground(new java.awt.Color(255, 255, 255));
        painelDadoPessoal.setPreferredSize(new java.awt.Dimension(632, 400));

        lblNome.setBackground(new java.awt.Color(255, 255, 255));
        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setText("Nome completo:");

        lblDtNasc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDtNasc.setText("Data de nascimento:");

        txtNome.setToolTipText("Insira o nome completo do paciente");

        dtDataNasc.setBackground(new java.awt.Color(255, 255, 255));

        lblRua.setBackground(new java.awt.Color(255, 255, 255));
        lblRua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRua.setText("Rua:");

        txtRua.setToolTipText("Insira o nome completo do paciente");
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });

        lblNum.setBackground(new java.awt.Color(255, 255, 255));
        lblNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNum.setText("Número:");

        txtNum.setToolTipText("Insira o nome completo do paciente");
        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        txtBairro.setToolTipText("Insira o nome completo do paciente");
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        lblBairro.setBackground(new java.awt.Color(255, 255, 255));
        lblBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBairro.setText("Bairro:");

        lblCidade.setBackground(new java.awt.Color(255, 255, 255));
        lblCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidade.setText("Cidade:");

        txtCidade.setToolTipText("Insira o nome completo do paciente");
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        lblEstado.setBackground(new java.awt.Color(255, 255, 255));
        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setText("Estado:");

        txtEstado.setToolTipText("Insira o nome completo do paciente");
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        lblCEP.setBackground(new java.awt.Color(255, 255, 255));
        lblCEP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCEP.setText("CEP:");

        txtCEP.setToolTipText("Insira o nome completo do paciente");
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        txtTel.setToolTipText("Insira o nome completo do paciente");
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });

        lblTel.setBackground(new java.awt.Color(255, 255, 255));
        lblTel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTel.setText("Telefone:");

        txtCel.setToolTipText("Insira o nome completo do paciente");
        txtCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelActionPerformed(evt);
            }
        });

        lblCel.setBackground(new java.awt.Color(255, 255, 255));
        lblCel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCel.setText("Celular:");

        txtEmail.setToolTipText("Insira o nome completo do paciente");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email:");

        javax.swing.GroupLayout painelDadoPessoalLayout = new javax.swing.GroupLayout(painelDadoPessoal);
        painelDadoPessoal.setLayout(painelDadoPessoalLayout);
        painelDadoPessoalLayout.setHorizontalGroup(
            painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadoPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoPessoalLayout.createSequentialGroup()
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoPessoalLayout.createSequentialGroup()
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCEP)
                            .addComponent(lblCEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome)
                                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBairro)
                                    .addComponent(lblBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(16, 16, 16))
        );
        painelDadoPessoalLayout.setVerticalGroup(
            painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblDtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblCel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoalLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );

        painelDados.add(painelDadoPessoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 270));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        painelDados.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 100, 30));

        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        painelDados.add(btnLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, 30));

        painelEnfermeiro.setBackground(new java.awt.Color(255, 255, 255));

        panelRX.setBackground(new java.awt.Color(255, 255, 255));
        panelRX.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Treinado Op Rx?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup2.add(rdSim1);
        rdSim1.setText("Sim");
        rdSim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSim1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdNao1);
        rdNao1.setText("Não");
        rdNao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRXLayout = new javax.swing.GroupLayout(panelRX);
        panelRX.setLayout(panelRXLayout);
        panelRXLayout.setHorizontalGroup(
            panelRXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdSim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdNao1)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        panelRXLayout.setVerticalGroup(
            panelRXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdSim1)
                .addComponent(rdNao1))
        );

        lblSetor1.setBackground(new java.awt.Color(255, 255, 255));
        lblSetor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSetor1.setText("Setor:");

        txtSetor1.setToolTipText("Insira o nome completo do paciente");
        txtSetor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetor1ActionPerformed(evt);
            }
        });

        lblCH1.setBackground(new java.awt.Color(255, 255, 255));
        lblCH1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCH1.setText("Carga Horária:");

        txtCH1.setToolTipText("Insira o nome completo do paciente");
        txtCH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCH1ActionPerformed(evt);
            }
        });

        panelGenero.setBackground(new java.awt.Color(255, 255, 255));
        panelGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gênero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup1.add(rdMasc);
        rdMasc.setText("Masculino");
        rdMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMascActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdFem);
        rdFem.setText("Feminino");

        javax.swing.GroupLayout panelGeneroLayout = new javax.swing.GroupLayout(panelGenero);
        panelGenero.setLayout(panelGeneroLayout);
        panelGeneroLayout.setHorizontalGroup(
            panelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdFem)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        panelGeneroLayout.setVerticalGroup(
            panelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneroLayout.createSequentialGroup()
                .addGroup(panelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMasc)
                    .addComponent(rdFem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelEnfermeiroLayout = new javax.swing.GroupLayout(painelEnfermeiro);
        painelEnfermeiro.setLayout(painelEnfermeiroLayout);
        painelEnfermeiroLayout.setHorizontalGroup(
            painelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnfermeiroLayout.createSequentialGroup()
                .addGroup(painelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnfermeiroLayout.createSequentialGroup()
                        .addGroup(painelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSetor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSetor1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelRX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        painelEnfermeiroLayout.setVerticalGroup(
            painelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnfermeiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnfermeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnfermeiroLayout.createSequentialGroup()
                        .addComponent(lblSetor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSetor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnfermeiroLayout.createSequentialGroup()
                        .addComponent(lblCH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        painelDados.add(painelEnfermeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 360, -1));

        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        painelDados.add(btnVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, 30));

        jTabbedPane1.addTab("Cadastrar", painelDados);

        panelCRUD.setBackground(new java.awt.Color(255, 255, 255));

        cmbEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnfermeirosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Selecione o enfermeiro:");

        painelDadoPessoal1.setBackground(new java.awt.Color(255, 255, 255));
        painelDadoPessoal1.setPreferredSize(new java.awt.Dimension(632, 400));

        lblNome1.setBackground(new java.awt.Color(255, 255, 255));
        lblNome1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome1.setText("Nome completo:");

        lblDtNasc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDtNasc1.setText("Data de nascimento:");

        txtNome1.setToolTipText("Insira o nome completo do paciente");

        dtDataNasc1.setBackground(new java.awt.Color(255, 255, 255));

        lblRua1.setBackground(new java.awt.Color(255, 255, 255));
        lblRua1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRua1.setText("Rua:");

        txtRua1.setToolTipText("Insira o nome completo do paciente");
        txtRua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRua1ActionPerformed(evt);
            }
        });

        lblNum1.setBackground(new java.awt.Color(255, 255, 255));
        lblNum1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNum1.setText("Número:");

        txtNum1.setToolTipText("Insira o nome completo do paciente");
        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });

        txtBairro1.setToolTipText("Insira o nome completo do paciente");
        txtBairro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairro1ActionPerformed(evt);
            }
        });

        lblBairro1.setBackground(new java.awt.Color(255, 255, 255));
        lblBairro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBairro1.setText("Bairro:");

        lblCidade1.setBackground(new java.awt.Color(255, 255, 255));
        lblCidade1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidade1.setText("Cidade:");

        txtCidade1.setToolTipText("Insira o nome completo do paciente");
        txtCidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidade1ActionPerformed(evt);
            }
        });

        lblEstado1.setBackground(new java.awt.Color(255, 255, 255));
        lblEstado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado1.setText("Estado:");

        txtEstado1.setToolTipText("Insira o nome completo do paciente");
        txtEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstado1ActionPerformed(evt);
            }
        });

        lblCEP1.setBackground(new java.awt.Color(255, 255, 255));
        lblCEP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCEP1.setText("CEP:");

        txtCEP1.setToolTipText("Insira o nome completo do paciente");
        txtCEP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEP1ActionPerformed(evt);
            }
        });

        txtTel1.setToolTipText("Insira o nome completo do paciente");
        txtTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTel1ActionPerformed(evt);
            }
        });

        lblTel1.setBackground(new java.awt.Color(255, 255, 255));
        lblTel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTel1.setText("Telefone:");

        txtCel1.setToolTipText("Insira o nome completo do paciente");
        txtCel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCel1ActionPerformed(evt);
            }
        });

        lblCel1.setBackground(new java.awt.Color(255, 255, 255));
        lblCel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCel1.setText("Celular:");

        txtEmail1.setToolTipText("Insira o nome completo do paciente");
        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });

        lblEmail1.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail1.setText("Email:");

        javax.swing.GroupLayout painelDadoPessoal1Layout = new javax.swing.GroupLayout(painelDadoPessoal1);
        painelDadoPessoal1.setLayout(painelDadoPessoal1Layout);
        painelDadoPessoal1Layout.setHorizontalGroup(
            painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoPessoal1Layout.createSequentialGroup()
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail1)
                            .addComponent(lblEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoPessoal1Layout.createSequentialGroup()
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCidade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCidade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEstado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEstado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCEP1)
                            .addComponent(lblCEP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome1)
                                    .addComponent(lblNome1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDtNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblRua1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRua1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNum1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNum1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBairro1)
                                    .addComponent(lblBairro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(16, 16, 16))
        );
        painelDadoPessoal1Layout.setVerticalGroup(
            painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(lblDtNasc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblRua1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblNum1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblBairro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblCidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblEstado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblCEP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadoPessoal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblTel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblCel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadoPessoal1Layout.createSequentialGroup()
                        .addComponent(lblEmail1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Gerenciar Enfermeiros");
        lblTitulo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        painelEnfermeiro1.setBackground(new java.awt.Color(255, 255, 255));

        panelRX1.setBackground(new java.awt.Color(255, 255, 255));
        panelRX1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Treinado Op Rx?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup2.add(rdSim2);
        rdSim2.setText("Sim");
        rdSim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSim2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdNao2);
        rdNao2.setText("Não");
        rdNao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNao2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRX1Layout = new javax.swing.GroupLayout(panelRX1);
        panelRX1.setLayout(panelRX1Layout);
        panelRX1Layout.setHorizontalGroup(
            panelRX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRX1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdSim2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdNao2)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        panelRX1Layout.setVerticalGroup(
            panelRX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdSim2)
                .addComponent(rdNao2))
        );

        lblSetor2.setBackground(new java.awt.Color(255, 255, 255));
        lblSetor2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSetor2.setText("Setor:");

        txtSetor2.setToolTipText("Insira o nome completo do paciente");
        txtSetor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetor2ActionPerformed(evt);
            }
        });

        lblCH2.setBackground(new java.awt.Color(255, 255, 255));
        lblCH2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCH2.setText("Carga Horária:");

        txtCH2.setToolTipText("Insira o nome completo do paciente");
        txtCH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCH2ActionPerformed(evt);
            }
        });

        panelGenero2.setBackground(new java.awt.Color(255, 255, 255));
        panelGenero2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gênero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup1.add(rdMasc2);
        rdMasc2.setText("Masculino");
        rdMasc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasc2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdFem2);
        rdFem2.setText("Feminino");

        javax.swing.GroupLayout panelGenero2Layout = new javax.swing.GroupLayout(panelGenero2);
        panelGenero2.setLayout(panelGenero2Layout);
        panelGenero2Layout.setHorizontalGroup(
            panelGenero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGenero2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdMasc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdFem2)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        panelGenero2Layout.setVerticalGroup(
            panelGenero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGenero2Layout.createSequentialGroup()
                .addGroup(panelGenero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMasc2)
                    .addComponent(rdFem2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelEnfermeiro1Layout = new javax.swing.GroupLayout(painelEnfermeiro1);
        painelEnfermeiro1.setLayout(painelEnfermeiro1Layout);
        painelEnfermeiro1Layout.setHorizontalGroup(
            painelEnfermeiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnfermeiro1Layout.createSequentialGroup()
                .addGroup(painelEnfermeiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnfermeiro1Layout.createSequentialGroup()
                        .addGroup(painelEnfermeiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSetor2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSetor2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnfermeiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCH2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCH2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelRX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGenero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        painelEnfermeiro1Layout.setVerticalGroup(
            painelEnfermeiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnfermeiro1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnfermeiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnfermeiro1Layout.createSequentialGroup()
                        .addComponent(lblSetor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSetor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnfermeiro1Layout.createSequentialGroup()
                        .addComponent(lblCH2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGenero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        btnAlterar.setText("Salvar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDLayout = new javax.swing.GroupLayout(panelCRUD);
        panelCRUD.setLayout(panelCRUDLayout);
        panelCRUDLayout.setHorizontalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cmbEnfermeiros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addComponent(painelDadoPessoal1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(painelEnfermeiro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove)
                        .addGap(284, 284, 284))))
        );
        panelCRUDLayout.setVerticalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEnfermeiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelEnfermeiro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDadoPessoal1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gerenciar", panelCRUD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Gerenciar Medicos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMascActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //Cadastrar novo enfermeiro

        try {
            String generoStr = null;
            boolean rx = false;

            if (rdMasc.isSelected()) {
                generoStr = rdMasc.getText().toLowerCase();
            } else if (rdFem.isSelected()) {
                generoStr = rdFem.getText().toLowerCase();
            }
            if (rdSim1.isSelected()) {
                rx = true;
            } else if (rdNao1.isSelected()) {
                rx = false;
            }
            Genero genero = Genero.valueOf(generoStr);
            
            //Criando instancia de endereco
            Endereco endereco = new Endereco(txtRua.getText(), Integer.parseInt(txtNum.getText()),
                    txtBairro.getText(), txtCidade.getText(), txtEstado.getText(), Integer.parseInt(txtCEP.getText()));
             
            //Criando instancia de contato
            ContatoTelEmail contato = new ContatoTelEmail(txtTel.getText(), txtCel.getText(), txtEmail.getText());
            
            //Criando instancia de enfermeiro e salvando na arraylist
            Enfermeiro enfermeiro = new Enfermeiro(rx, txtSetor1.getText(), Integer.parseInt(txtCH1.getText()), txtNome.getText(), dtDataNasc.getDate(), endereco, contato, genero);
            HomePage.enfermeiros.add(enfermeiro);
            
            JOptionPane.showMessageDialog(null, txtNome.getText() + " foi cadastrado(a) com sucesso!");
            
            //Atualizando combobox
            dm.addElement(enfermeiro.getNomeCompleto());
            cmbEnfermeiros.setModel(dm);
            cmbEnfermeiros.setSelectedIndex(0);
            
            //Limpando os campos
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage() + " favor preencher corretamente os dados!");

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cmbEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnfermeirosActionPerformed
        // Inserindo os dados de acordo com o enfermeiro selecionado
        clearFields2();
        int index = cmbEnfermeiros.getSelectedIndex();
        txtNome1.setText(HomePage.enfermeiros.get(index).getNomeCompleto());
        txtBairro1.setText(HomePage.enfermeiros.get(index).getEndereco().getBairro());
        txtCEP1.setText(String.valueOf(HomePage.enfermeiros.get(index).getEndereco().getCep()));
        txtCel1.setText(HomePage.enfermeiros.get(index).getContato().getCelular());
        txtCidade1.setText(HomePage.enfermeiros.get(index).getEndereco().getCidade());
        txtEmail1.setText(HomePage.enfermeiros.get(index).getContato().getEmail());
        txtEstado1.setText(HomePage.enfermeiros.get(index).getEndereco().getEstado());
        txtNum1.setText(String.valueOf(HomePage.enfermeiros.get(index).getEndereco().getNumero()));
        txtRua1.setText(HomePage.enfermeiros.get(index).getEndereco().getRua());
        txtTel1.setText(HomePage.enfermeiros.get(index).getContato().getTelefone());
        dtDataNasc1.setDate(HomePage.enfermeiros.get(index).getDataNascimento());
        if (HomePage.enfermeiros.get(index).getGenero() == Genero.masculino) {
            rdMasc2.setSelected(true);
            rdFem2.setSelected(false);
        } else {
            rdFem2.setSelected(true);
            rdMasc2.setSelected(false);
        }
        if (HomePage.enfermeiros.get(index).isTreinadoOpRX()) {
            rdSim2.setSelected(true);
            rdNao2.setSelected(false);
        } else {
            rdNao2.setSelected(true);
            rdSim2.setSelected(false);
        }
        txtSetor2.setText(HomePage.enfermeiros.get(index).getSetor());
        txtCH2.setText(String.valueOf(HomePage.enfermeiros.get(index).getChSemanal()));

    }//GEN-LAST:event_cmbEnfermeirosActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        //Voltar ao menu
        dispose();       
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        //Remove o enfermeiro selecionado
        try {
            int index = cmbEnfermeiros.getSelectedIndex();
            HomePage.enfermeiros.remove(index);
            preencherComboBox();
            clearFields2();
            JOptionPane.showMessageDialog(null, "O enfermeiro foi removido com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage() + " tente novamente.");
        }


    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Altera as informações do enfermeiro de acordo com os campos
        try {
            int index = cmbEnfermeiros.getSelectedIndex();
            HomePage.enfermeiros.get(index).setNomeCompleto(txtNome1.getText());
            HomePage.enfermeiros.get(index).setDataNascimento(dtDataNasc1.getDate());
            HomePage.enfermeiros.get(index).getEndereco().setRua(txtRua1.getText());
            HomePage.enfermeiros.get(index).getEndereco().setNumero(Integer.parseInt(txtNum1.getText()));
            HomePage.enfermeiros.get(index).getEndereco().setBairro(txtBairro1.getText());
            HomePage.enfermeiros.get(index).getEndereco().setCidade(txtCidade1.getText());
            HomePage.enfermeiros.get(index).getEndereco().setEstado(txtEstado1.getText());
            HomePage.enfermeiros.get(index).getEndereco().setCep(Integer.parseInt(txtCEP1.getText()));
            HomePage.enfermeiros.get(index).getContato().setTelefone(txtTel1.getText());
            HomePage.enfermeiros.get(index).getContato().setCelular(txtCel1.getText());
            HomePage.enfermeiros.get(index).getContato().setEmail(txtEmail1.getText());
            if (rdMasc2.isSelected()) {
                HomePage.enfermeiros.get(index).setGenero(Genero.masculino);
            } else if (rdFem2.isSelected()) {
                HomePage.enfermeiros.get(index).setGenero(Genero.feminino);
            }
            HomePage.enfermeiros.get(index).setSetor(txtSetor2.getText());
            HomePage.enfermeiros.get(index).setChSemanal(Integer.parseInt(txtCH2.getText()));
            if (rdSim2.isSelected()) {
                HomePage.enfermeiros.get(index).setTreinadoOpRX(true);
            } else if (rdNao2.isSelected()) {
                HomePage.enfermeiros.get(index).setTreinadoOpRX(false);
            }

            JOptionPane.showMessageDialog(null, txtNome1.getText() + " foi alterado(a) com sucesso!");
            preencherComboBox();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage() + " favor preencher corretamente os dados!");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtRua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRua1ActionPerformed

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void txtBairro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairro1ActionPerformed

    private void txtCidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidade1ActionPerformed

    private void txtEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstado1ActionPerformed

    private void txtCEP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEP1ActionPerformed

    private void txtTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel1ActionPerformed

    private void txtCel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCel1ActionPerformed

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void rdSim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSim1ActionPerformed

    private void rdNao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNao1ActionPerformed

    private void txtSetor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetor1ActionPerformed

    private void txtCH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCH1ActionPerformed

    private void rdSim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSim2ActionPerformed

    private void rdNao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNao2ActionPerformed

    private void txtSetor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetor2ActionPerformed

    private void txtCH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCH2ActionPerformed

    private void rdMasc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasc2ActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarEnfermeiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JToggleButton btnVoltar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbEnfermeiros;
    private com.toedter.calendar.JDateChooser dtDataNasc;
    private com.toedter.calendar.JDateChooser dtDataNasc1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBairro1;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCEP1;
    private javax.swing.JLabel lblCH1;
    private javax.swing.JLabel lblCH2;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblDtNasc1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblRua1;
    private javax.swing.JLabel lblSetor1;
    private javax.swing.JLabel lblSetor2;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel painelDadoPessoal;
    private javax.swing.JPanel painelDadoPessoal1;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelEnfermeiro;
    private javax.swing.JPanel painelEnfermeiro1;
    private javax.swing.JPanel panelCRUD;
    private javax.swing.JPanel panelGenero;
    private javax.swing.JPanel panelGenero2;
    private javax.swing.JPanel panelRX;
    private javax.swing.JPanel panelRX1;
    private javax.swing.JRadioButton rdFem;
    private javax.swing.JRadioButton rdFem2;
    private javax.swing.JRadioButton rdMasc;
    private javax.swing.JRadioButton rdMasc2;
    private javax.swing.JRadioButton rdNao1;
    private javax.swing.JRadioButton rdNao2;
    private javax.swing.JRadioButton rdSim1;
    private javax.swing.JRadioButton rdSim2;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairro1;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCEP1;
    private javax.swing.JTextField txtCH1;
    private javax.swing.JTextField txtCH2;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCel1;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidade1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstado1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtRua1;
    private javax.swing.JTextField txtSetor1;
    private javax.swing.JTextField txtSetor2;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTel1;
    // End of variables declaration//GEN-END:variables
}
